spring.application.name=cckcakesandbakery

################### Data Base Configuration Details  #####################


# driver:servername://hostname:portno/databasename
spring.datasource.url =jdbc:MYSQL://localhost:3306/cckcakesandbakery
spring.datasource.username=root
spring.datasource.password=12345

# If this is true, we cannot get a single object.This avoids returning an empty object
spring.jackson.serialization.fail-on-empty-beans= false


#  server port
# server port = 

# Database is updated by compairin entities and existing database ---> used when reverse engineering
# spring.jpa.hibernate.ddl-auto= update
